apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigw-pod
  template:
    metadata:
      labels:
        app: ocelotapigw-pod
    spec:
      containers:
        - name: ocelotapi-container
          image: crmohan74/aspneteshopper:ocelotapigw
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
#           - name: ElasticConfiguration__Uri
#              value: "http://elasticsearch:9200"