---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aspnetrunbasicsapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetrunbasicsapi-pod
  template:
    metadata:
      labels:
        app: aspnetrunbasicsapi-pod
    spec:
      containers:
      - name: aspnetrunbasicsapi-container
        image: crmohan74/aspneteshopper:aspnetrunbasics
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ApiSettings__GatewayAddress
            valueFrom:
                configMapKeyRef:
                  name: aspnetrunbasicsapi-configmap
                  key: ocelotapigw-url
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetrunbasicsapi-service
spec:
  selector:
    app: aspnetrunbasicsapi-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
