apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi-pod
  template:
    metadata:
      labels:
        app: basketapi-pod
    spec:
      containers:
        - name: basketapi-container
          image: crmohan74/aspneteshopper:basketapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              value: redisdb-service:6379
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  type: NodePort
  selector:
    app: basketapi-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80    
