apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
  selector:
    app: catalogapi-pod