apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb-pod
  template:
    metadata:
      labels:
        app: catalogdb-pod
    spec:
      containers:
      - name: catalogdb-container
        image: mongo
        ports:
          - containerPort: 27017
            name: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-username                  
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-root-password